// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://glgcnymigakooloqmbtk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdsZ2NueW1pZ2Frb29sb3FtYnRrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTczNjEwNTgsImV4cCI6MjA3MjkzNzA1OH0.Dh7JrFVVhcVyG9mckwqDlQzzRkbFaQhFQ8QdK_bpkeQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});